sudo: false
language: bash
os:
  - linux

addons:
  apt:
    packages:
      - gperf
      - python
      - python-serial

before_install:
  # Save path to the git respository
  - PROJECT_PATH=$(pwd)

install:
  # Install ESP32 toochain following steps as desribed
  # in http://esp-idf.readthedocs.io/en/latest/linux-setup.html
  #
  # Get required packages - already done above, see addons: apt: packages:
  # - sudo apt-get install git wget make libncurses-dev flex bison gperf python python-serial
  # Prepare directory for the toolchain
  git submodule update --init --recursive

script:
  # Update configuration so that kconfig doesn't start interactive mode
  - make defconfig
  # Build project from the git repository
  - make

notifications:
  irc:
    channels:
      - "chat.freenode.net#sha2017-badge"
      - "chat.freenode.net#sha2017-badge-dev"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true
